version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      days: 3
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    cooldown:
      days: 3
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      days: 3
    groups:
      abinnovision:
        patterns:
          - "@abinnovision/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      fortawesome:
        patterns:
          - "@fortawesome/*"
      next:
        patterns:
          - "@next/*"
          - "next"
      heroui:
        patterns:
          - "@heroui/*"
      drizzle:
        patterns:
          - "drizzle-kit"
          - "drizzle-orm"
      prisma:
        patterns:
          - "@prisma/client"
          - "prisma"
      storybook:
        patterns:
          - "@storybook/*"
          - "storybook"
      radix:
        patterns:
          - "@radix-ui/*"
