version: "3.8"

services:
  # Main development container
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/openllm:cached
    command: sleep infinity
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:pw@postgres:5432/db

  # Use the existing PostgreSQL service from the main docker-compose.yml
  postgres:
    image: postgres:17-alpine
    command: postgres -c log_statement=all
    restart: always
    ports:
      - "5389:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: db
    volumes:
      - ../packages/db/init:/docker-entrypoint-initdb.d
