version: "3.8"

services:
  # Main development container
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/openllm:cached
    command: sleep infinity
    network_mode: service:postgres
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:pw@localhost:5389/db

  # Use the existing PostgreSQL service from the main docker-compose.yml
  postgres:
    extends:
      file: ../docker-compose.yml
      service: postgres
    # Keep the original port mapping
    ports:
      - "5389:5432"
