name: ci

on: pull_request_target

jobs:
  autofix:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'dependabot[bot]' }}

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Autofix
        uses: steebchen/actions/autofix@v0.7.1
        with:
          token: ${{ secrets.GH_TOKEN }}
