name: ci

on: pull_request

jobs:
  autofix:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'steebchen' }}

    steps:
      - name: Autofix
        uses: steebchen/actions/autofix@v0.12.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          format-command: pnpm generate
