name: pr

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: steebchen/action-auto-semantic-pull-request@main
        with:
          aiApiKey: ${{ secrets.PR_MESSAGE_LLM_GATEWAY_API_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
