name: prepare

on:
  workflow_call:
    inputs:
      cmd:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Collect versions
        run: |
          echo "nodejs_version=$(cat .tool-versions | grep 'nodejs' | cut -d ' ' -f 2)" >> "$GITHUB_ENV"
          echo "pnpm_version=$(cat .tool-versions | grep 'pnpm' | cut -d ' ' -f 2)" >> "$GITHUB_ENV"

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.pnpm_version }}

      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.nodejs_version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: ${{ inputs.cmd }}
        run: |
          set -eux
          ${{ inputs.cmd }}
        env:
          LLM_OPENAI_API_KEY: ${{ secrets.LLM_OPENAI_API_KEY }}
          LLM_ANTHROPIC_API_KEY: ${{ secrets.LLM_ANTHROPIC_API_KEY }}
          LLM_INFERENCE_NET_API_KEY: ${{ secrets.LLM_INFERENCE_NET_API_KEY }}
          LLM_TOGETHER_AI_API_KEY: ${{ secrets.LLM_TOGETHER_AI_API_KEY }}
          LLM_GOOGLE_AI_STUDIO_API_KEY: ${{ secrets.LLM_GOOGLE_AI_STUDIO_API_KEY }}
          LLM_CLOUD_RIFT_API_KEY: ${{ secrets.LLM_CLOUD_RIFT_API_KEY }}
          LLM_MISTRAL_API_KEY: ${{ secrets.LLM_MISTRAL_API_KEY }}
          LLM_X_AI_API_KEY: ${{ secrets.LLM_X_AI_API_KEY }}
          LLM_GROQ_API_KEY: ${{ secrets.LLM_GROQ_API_KEY }}
          LLM_DEEPSEEK_API_KEY: ${{ secrets.LLM_DEEPSEEK_API_KEY }}
          LLM_PERPLEXITY_API_KEY: ${{ secrets.LLM_PERPLEXITY_API_KEY }}
          LLM_NOVITA_AI_API_KEY: ${{ secrets.LLM_NOVITA_AI_API_KEY }}
          LLM_MOONSHOT_API_KEY: ${{ secrets.LLM_MOONSHOT_API_KEY }}
          LLM_ALIBABA_API_KEY: ${{ secrets.LLM_ALIBABA_API_KEY }}
          LLM_NEBIUS_API_KEY: ${{ secrets.LLM_NEBIUS_API_KEY }}
          LLM_Z_AI_API_KEY: ${{ secrets.LLM_Z_AI_API_KEY }}
          LLM_ROUTEWAY_API_KEY: ${{ secrets.LLM_ROUTEWAY_API_KEY }}
          LLM_ROUTEWAY_DISCOUNT_API_KEY: ${{ secrets.LLM_ROUTEWAY_DISCOUNT_API_KEY }}
          LLM_ROUTEWAY_DISCOUNT_BASE_URL: ${{ secrets.LLM_ROUTEWAY_DISCOUNT_BASE_URL }}
