name: ci

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Collect versions
        run: |
          echo "nodejs_version=$(cat .tool-versions | grep 'nodejs' | cut -d ' ' -f 2)" >> "$GITHUB_ENV"
          echo "pnpm_version=$(cat .tool-versions | grep 'pnpm' | cut -d ' ' -f 2)" >> "$GITHUB_ENV"
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.pnpm_version }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.nodejs_version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Compose
        run: |
          docker compose up -d
          sleep 5
      - name: Prepare
        run: pnpm test-prepare
      - name: Test
        run: pnpm test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
